const ApiRoutes = {
    Register:{
        path:"user/createuser",
        authenticate:false
    },
    Login:{
        path:"user/login",
        authenticate:false
    },
    Forget_password:{
        path:"user/forgetpassword",
        authenticate:false
    },
    Check_password:{
        path:"user/checkforgetpassword",
        authenticate:false
    },
    Change_forget_password:{
        path:"user/changeforgetpassword",
        authenticate:false
    },
    getusers:{
        path:"user/getusers",
        authenticate:true
    },
    addplaces:{
        path:"user/createplaces",
        authenticate:true
    },
    getPlaces:{
        path:"user/getplaces",
        authenticate:true
    },
    getuserplaces:{
        path:"user/getuserplaces",
        authenticate:false
    },
    getplacesbyid:{
        path:"user/getplacesbyid",
        authenticate:true
    },
    deleteplacebyid:{
        path:"user/deleteplacebyid",
        authenticate:true
    },
    editplacebyid:{
        path:"user/editplacebyid",
        authenticate:true
    },
    booking:
    {
        path:"user/booking",
        authenticate:true
    },
    getuserbyid:{
        path:"user/getprofile",
        authenticate:true
    },
    cancelbooking:{
        path:"user/cancelbooking",
        authenticate:true
    },
    getkey:{
        path:"user/paymentprocess",
        authenticate:true
    },
    getpayment:{
        path:"user/payment",
        authenticate:true
    },
    conformpayment:{
        path:"user/confirmbooking",
        authenticate:true
    }
}


export default ApiRoutes